export default {
  SET_BUSINESSES: 'SET_BUSINESSES',
  APPEND_BUSINESSES: 'APPEND_BUSINESSES',
  SET_LOCATION: 'SET_LOCATION',
  LOAD_MORE: 'LOAD_MORE',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
}